import fs from "node:fs";
import path from "node:path";
import { decisionId, type LoadedHandoff } from "./intake";

const allowed = "accept | reject | defer | needs-research | accept-with-edits";

export function renderReview({ handoff, hash }: LoadedHandoff) {
  const lines = [
    `# Research review: ${handoff.run.id}`,
    "",
    `> Generated from handoff hash \`${hash}\`. Do not edit this file by hand.`,
    "",
    "## Question",
    "",
    handoff.run.question,
    "",
    "## Synthesis",
    "",
    handoff.run.synthesis,
    "",
    "## Proposed changes and evidence",
    "",
  ];
  for (const finding of handoff.findings) {
    lines.push(
      `### ${finding.id}`,
      "",
      finding.statement,
      "",
      `- Classification: **${finding.classification}** (advisory; no automatic merge or promotion)`,
      `- Evidence: **${finding.evidenceStance}**; quality **${finding.evidenceQuality}**`,
      `- Generalized applicability: **${finding.generalizedApplicability ? "yes" : "no"}**`,
      `- Sources: ${finding.sourceIds.map((id) => `\`${id}\``).join(", ")}`,
      `- Suggested targets: ${finding.suggestedTargets.length ? finding.suggestedTargets.map((id) => `\`${id}\``).join(", ") : "none"}`,
      `- Existing Claim candidates: ${finding.existingClaimCandidates?.length ? finding.existingClaimCandidates.map((id) => `\`${id}\``).join(", ") : "none"}`,
      `- Proposed Claim: ${finding.proposedClaim ? `\`${finding.proposedClaim.id}\` — ${finding.proposedClaim.statement}` : "none"}`,
      `- Uncertainty: ${finding.uncertainty ?? "none recorded"}`,
      "",
      `**Decision \`${decisionId(handoff.run.id, finding.id)}\`**`,
      "",
      `Allowed response: ${allowed}.`,
      "",
    );
  }
  lines.push("## Open questions", "");
  if (!handoff.questions.length) lines.push("None.", "");
  handoff.questions.forEach((question) => lines.push(`- **${question.id}:** ${question.question}`));
  lines.push("", "## Sources", "");
  handoff.sources.forEach((source) => lines.push(`- **${source.id}** (${source.access}, ${source.kind}): ${source.title}; identity \`${source.identity}\`.`));
  lines.push("", "## Canonical change gate", "", "No canonical change is authorized by this packet. Create a decision file, validate it, and apply accepted decisions in a separate model-change pull request referencing the run and decision IDs.", "");
  return lines.join("\n");
}

export function writeReviews(handoffs: LoadedHandoff[], root = process.cwd()) {
  const directory = path.join(root, "research", "reviews");
  fs.mkdirSync(directory, { recursive: true });
  const expected = new Set<string>();
  handoffs.forEach((loaded) => {
    const file = path.join(directory, `${loaded.handoff.run.id}.md`);
    fs.writeFileSync(file, renderReview(loaded));
    expected.add(path.basename(file));
  });
  fs.readdirSync(directory).filter((name) => name.endsWith(".md") && !expected.has(name)).forEach((name) => fs.rmSync(path.join(directory, name)));
}
